<map id="armor_api.armor_exceptions.ArmorServiceCallError" name="armor_api.armor_exceptions.ArmorServiceCallError">
<area shape="rect" id="node1" title=" " alt="" coords="5,169,219,211"/>
<area shape="rect" id="node2" href="$classarmor__api_1_1armor__exceptions_1_1_armor_py_exception.html" title=" " alt="" coords="5,80,219,121"/>
<area shape="rect" id="node3" title=" " alt="" coords="69,5,155,32"/>
</map>
